# Generated by Django 4.1.4 on 2023-01-17 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amidastyle', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='telegram_id',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='telegram_id',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='telegram_id',
            new_name='user_id',
        ),
    ]
